### ISSUE TITLE
web3_1.default is not a constructor

### ISSUE THREAD

**Issue by netSKY123** [owl1n/nestjs-web3#1]
With a fresh NestJS application, I install directly after the nestjs-web3 dependency. 
I ut the minimal config as typed in the readme, the run of the app failed. 

`web3_1.default is not a constructor`

It looks like an issue between CommonJS and ESM modules no?

**Comment by netSKY123** [comment]
It seems the `web3-client.provider.js` is transpiled with the .default constructor

```
const getClient = async (options) => {
    const { url } = options;
    return new web3_1.default(url);
};
```

When I remove the default, everything is working fine. 
What should I change in my config?

**Comment by maorstamati** [comment]
I faced the same issue and I think the solution is as suggested here: https://github.com/ChainSafe/web3.js/issues/4301

**Comment by nxic** [comment]
#2 added `esModuleInterop` to the `tsconfig.json` as @maorstamati suggested and It works fine for me.

**Comment by owl1n** [comment]
thank you @nxic for pull request. Merged and new version published.

v1.1.3 released now with fixes
